name: WebRTCMessenger
author: Christian Hotz-Behofsits <chris.hotz.behofsits@gmail.com>
version: 0.0.1
homepage: https://github.com/inkrement/messenger
description: A Webrtc Messenger
environment:
  sdk: '>0.8.7'
dependencies:
  browser: any
  browser_detect: any
  js: any
  json: any
dev_dependencies:
  logging: any
  unittest: any
