name: messenger
version: 0.0.2
author: Christian Hotz-Behofsits <chris.hotz.behofsits@gmail.com>
description: A massaging library for dart. incl. TCP Signaling and WebRTC communication.
homepage: https://github.com/inkrement/messenger
environment:
  sdk: '>0.8.7'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  json: '>=0.9.1 <0.10.0'
dev_dependencies:
  logging: any
  unittest: any
