name: WebRTCMessenger
version: 0.0.1
author: Christian Hotz-Behofsits <chris.hotz.behofsits@gmail.com>
description: A Webrtc Messenger
homepage: https://github.com/inkrement/messenger
environment:
  sdk: '>0.8.7'
dependencies:
  browser: any
  json: any
dev_dependencies:
  logging: any
  unittest: any
