name: webrtc
author: Christian Hotz-Behofsits <chris.hotz.behofsits@gmail.com>
version: 0.0.1
description: A sample web application
environment:
  sdk: '>0.8.7'
dependencies:
  browser: any
  browser_detect: any
  js: any
  json: any
  logging: any
  serialization: any
  unittest: any
